name: github pages

on:
    push:
      branches:
        - main  # Set a branch that will trigger a deployment
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: latest
                  # extended: true

            - name: Build Web
              run: hugo --gc --minify

            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                  PERSONAL_TOKEN: ${{ secrets.KIMS_TOKEN }}
                  PUBLISH_DIR: ./public
                  commit_message: ${{ github.event.head_commit.message }}
